import type { DailyReadingRef } from '@/types/bible';

export const DAILY_READINGS: DailyReadingRef[] = [
  { bookId: 'PSA', chapter: 23, label: 'El Señor es mi pastor' },
  { bookId: 'JHN', chapter: 3, verseStart: 16, verseEnd: 21, label: 'De tal manera amó Dios al mundo' },
  { bookId: 'PHP', chapter: 4, verseStart: 6, verseEnd: 7, label: 'La paz de Dios' },
  { bookId: 'PRO', chapter: 3, verseStart: 5, verseEnd: 6, label: 'Confía en el Señor' },
  { bookId: 'ROM', chapter: 8, verseStart: 28, label: 'Todas las cosas ayudan a bien' },
  { bookId: 'MAT', chapter: 5, verseStart: 1, verseEnd: 12, label: 'Las bienaventuranzas' },
  { bookId: 'ISA', chapter: 40, verseStart: 28, verseEnd: 31, label: 'Los que esperan en Jehová' },
  { bookId: 'JOS', chapter: 1, verseStart: 8, verseEnd: 9, label: 'Sé fuerte y valiente' },
  { bookId: '1CO', chapter: 13, label: 'El amor es sufrido, es benigno' },
  { bookId: 'EPH', chapter: 2, verseStart: 8, verseEnd: 10, label: 'Por gracia sois salvos' },
  { bookId: 'GAL', chapter: 5, verseStart: 22, verseEnd: 23, label: 'El fruto del Espíritu' },
  { bookId: 'HEB', chapter: 11, verseStart: 1, label: 'La fe es la sustancia' },
  { bookId: 'JAS', chapter: 1, verseStart: 2, verseEnd: 4, label: 'Gozo en las pruebas' },
  { bookId: '1PE', chapter: 5, verseStart: 7, label: 'Echando toda vuestra ansiedad' },
  { bookId: 'PSA', chapter: 91, verseStart: 1, verseEnd: 2, label: 'El que habita al abrigo del Altísimo' },
  { bookId: 'PSA', chapter: 46, verseStart: 1, label: 'Dios es nuestro amparo' },
  { bookId: 'PSA', chapter: 119, verseStart: 105, label: 'Lámpara es a mis pies tu palabra' },
  { bookId: 'PSA', chapter: 27, verseStart: 1, label: 'Jehová es mi luz' },
  { bookId: 'PRO', chapter: 18, verseStart: 10, label: 'Torre fuerte es el nombre de Jehová' },
  { bookId: 'ECC', chapter: 3, verseStart: 1, verseEnd: 8, label: 'Tiempo para todo' },
  { bookId: 'MIC', chapter: 6, verseStart: 8, label: 'Hacer justicia y amar misericordia' },
  { bookId: 'LUK', chapter: 15, verseStart: 11, verseEnd: 24, label: 'El hijo pródigo' },
  { bookId: 'MRK', chapter: 4, verseStart: 35, verseEnd: 41, label: 'Jesús calma la tempestad' },
  { bookId: 'MAT', chapter: 6, verseStart: 9, verseEnd: 13, label: 'El Padrenuestro' },
  { bookId: 'JHN', chapter: 14, verseStart: 1, verseEnd: 6, label: 'Yo soy el camino' },
  { bookId: 'JHN', chapter: 10, verseStart: 10, label: 'Vida en abundancia' },
  { bookId: 'ROM', chapter: 12, verseStart: 1, verseEnd: 2, label: 'Transformados por la renovación' },
  { bookId: '2TI', chapter: 1, verseStart: 7, label: 'Espíritu de poder y de amor' },
  { bookId: 'COL', chapter: 3, verseStart: 12, verseEnd: 14, label: 'Vestíos de entrañable misericordia' },
  { bookId: 'REV', chapter: 21, verseStart: 4, label: 'Enjugará Dios toda lágrima' },
];
